"""Skill manifest — discover and index every skill shipped under ``skills/``.

The manifest is a single JSON file at ``<repo>/skills/manifest.json`` plus a
typed in-memory representation. It is regenerated by ``rh skill index`` and
read by every other ``rh skill`` subcommand.

Manifest schema (v1):

    {
      "schema_version": "1.0",
      "generated_at": "<ISO-8601 UTC>",
      "skills_dir": "skills",
      "skills": [
        {
          "name": "paper-writing",
          "path": "skills/paper-writing",
          "skill_md": "skills/paper-writing/SKILL.md",
          "description": "<flattened, single-line>",
          "category": "writing",          # optional
          "version": "1.0.0",             # optional
          "tracks": ["original-research", "survey-review", ...],  # optional
          "allowed_tools": [...],         # optional, copied through
          "extras": {...}                  # any other front-matter keys
        }
      ]
    }

Front-matter parsing is intentionally lenient — we accept any YAML keys but
only ``name`` and ``description`` are required. Triggers are not a separate
field; agents that need natural-language triggers parse them out of
``description`` (the convention the existing skills already use).
"""

from __future__ import annotations

import dataclasses
import datetime as _dt
import json
import re
from pathlib import Path
from typing import Any, Iterable

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover - yaml is in deps but be tolerant
    yaml = None  # type: ignore


SCHEMA_VERSION = "1.0"
DEFAULT_SKILLS_DIRNAME = "skills"
MANIFEST_FILENAME = "manifest.json"


@dataclasses.dataclass
class SkillRecord:
    """One skill entry in the manifest."""

    name: str
    path: str  # repo-relative path to the skill directory
    skill_md: str  # repo-relative path to SKILL.md
    description: str
    category: str | None = None
    version: str | None = None
    tracks: list[str] = dataclasses.field(default_factory=list)
    allowed_tools: list[str] = dataclasses.field(default_factory=list)
    extras: dict[str, Any] = dataclasses.field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {
            "name": self.name,
            "path": self.path,
            "skill_md": self.skill_md,
            "description": self.description,
        }
        if self.category:
            out["category"] = self.category
        if self.version:
            out["version"] = self.version
        if self.tracks:
            out["tracks"] = list(self.tracks)
        if self.allowed_tools:
            out["allowed_tools"] = list(self.allowed_tools)
        if self.extras:
            out["extras"] = dict(self.extras)
        return out

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SkillRecord":
        return cls(
            name=data["name"],
            path=data["path"],
            skill_md=data["skill_md"],
            description=data.get("description", ""),
            category=data.get("category"),
            version=data.get("version"),
            tracks=list(data.get("tracks") or []),
            allowed_tools=list(data.get("allowed_tools") or []),
            extras=dict(data.get("extras") or {}),
        )


@dataclasses.dataclass
class SkillManifest:
    schema_version: str
    generated_at: str
    skills_dir: str
    skills: list[SkillRecord]

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "generated_at": self.generated_at,
            "skills_dir": self.skills_dir,
            "skills": [s.to_dict() for s in self.skills],
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SkillManifest":
        return cls(
            schema_version=data.get("schema_version", SCHEMA_VERSION),
            generated_at=data.get("generated_at", ""),
            skills_dir=data.get("skills_dir", DEFAULT_SKILLS_DIRNAME),
            skills=[SkillRecord.from_dict(s) for s in data.get("skills", [])],
        )

    def get(self, name: str) -> SkillRecord | None:
        for s in self.skills:
            if s.name == name:
                return s
        return None

    def names(self) -> list[str]:
        return [s.name for s in self.skills]


# ----------------------------- parsing ---------------------------------------

_FRONTMATTER_RE = re.compile(
    r"^---\s*\n(?P<body>.*?)\n---\s*\n",
    re.DOTALL,
)


def _parse_frontmatter(text: str) -> dict[str, Any]:
    """Extract YAML front-matter from a SKILL.md document.

    Returns an empty dict if no front-matter is present. Falls back to a
    minimal ``key: value`` parser if PyYAML is unavailable, which is enough
    for the simple ``name``/``description`` fields the existing skills use.
    """

    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}
    raw = match.group("body")
    if yaml is not None:
        try:
            data = yaml.safe_load(raw) or {}
            if isinstance(data, dict):
                return data
        except Exception:
            pass
    # naive fallback: only handles ``key: scalar`` lines
    out: dict[str, Any] = {}
    for line in raw.splitlines():
        if ":" not in line or line.lstrip().startswith("#"):
            continue
        key, _, value = line.partition(":")
        out[key.strip()] = value.strip().strip('"').strip("'")
    return out


def _flatten_description(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return " ".join(value.split())
    if isinstance(value, list):
        return " ".join(_flatten_description(v) for v in value)
    return str(value)


def _detect_tracks(skill_dir: Path) -> list[str]:
    tracks_dir = skill_dir / "tracks"
    if not tracks_dir.is_dir():
        return []
    out = []
    for p in sorted(tracks_dir.iterdir()):
        if p.is_file() and p.suffix.lower() in {".md", ".markdown"}:
            out.append(p.stem)
    return out


# ----------------------------- build / io ------------------------------------


def build_manifest(
    repo_root: Path,
    skills_dirname: str = DEFAULT_SKILLS_DIRNAME,
) -> SkillManifest:
    """Scan ``<repo_root>/<skills_dirname>/`` and return a manifest.

    A directory is considered a skill if it contains a top-level ``SKILL.md``.
    Hidden directories and the manifest file itself are ignored.
    """

    skills_dir = repo_root / skills_dirname
    if not skills_dir.is_dir():
        raise FileNotFoundError(f"skills directory not found: {skills_dir}")

    records: list[SkillRecord] = []
    for entry in sorted(skills_dir.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        skill_md = entry / "SKILL.md"
        if not skill_md.is_file():
            continue

        try:
            text = skill_md.read_text(encoding="utf-8")
        except OSError:
            continue
        fm = _parse_frontmatter(text)

        name = str(fm.get("name") or entry.name).strip()
        description = _flatten_description(fm.get("description") or "")
        category = fm.get("category")
        version = fm.get("version")
        allowed_tools = fm.get("allowed-tools") or fm.get("allowed_tools") or []
        if isinstance(allowed_tools, str):
            allowed_tools = [allowed_tools]

        consumed_keys = {
            "name",
            "description",
            "category",
            "version",
            "allowed-tools",
            "allowed_tools",
        }
        extras = {k: v for k, v in fm.items() if k not in consumed_keys}

        record = SkillRecord(
            name=name,
            path=str(entry.relative_to(repo_root)),
            skill_md=str(skill_md.relative_to(repo_root)),
            description=description,
            category=str(category) if category else None,
            version=str(version) if version else None,
            tracks=_detect_tracks(entry),
            allowed_tools=[str(t) for t in allowed_tools],
            extras=extras,
        )
        records.append(record)

    manifest = SkillManifest(
        schema_version=SCHEMA_VERSION,
        generated_at=_dt.datetime.now(tz=_dt.timezone.utc)
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z"),
        skills_dir=skills_dirname,
        skills=records,
    )
    return manifest


def manifest_path(
    repo_root: Path, skills_dirname: str = DEFAULT_SKILLS_DIRNAME
) -> Path:
    return repo_root / skills_dirname / MANIFEST_FILENAME


def write_manifest(
    manifest: SkillManifest,
    repo_root: Path,
    skills_dirname: str = DEFAULT_SKILLS_DIRNAME,
) -> Path:
    target = manifest_path(repo_root, skills_dirname)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(manifest.to_dict(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return target


def load_manifest(
    repo_root: Path,
    skills_dirname: str = DEFAULT_SKILLS_DIRNAME,
) -> SkillManifest:
    path = manifest_path(repo_root, skills_dirname)
    if not path.is_file():
        raise FileNotFoundError(
            f"manifest not found at {path}; run `rh skill index` first"
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    return SkillManifest.from_dict(data)


# ----------------------------- helpers ---------------------------------------


def find_repo_root(start: Path | None = None) -> Path:
    """Walk up from ``start`` looking for a directory that contains ``skills/``.

    Falls back to the package's own repo (if installed editable from a clone).
    Raises FileNotFoundError if neither is found.
    """

    here = (start or Path.cwd()).resolve()
    for candidate in [here, *here.parents]:
        if (candidate / DEFAULT_SKILLS_DIRNAME).is_dir() and any(
            (candidate / DEFAULT_SKILLS_DIRNAME).glob("*/SKILL.md")
        ):
            return candidate

    # Fallback: try the installed package's source tree
    pkg = Path(__file__).resolve()
    for candidate in pkg.parents:
        if (candidate / DEFAULT_SKILLS_DIRNAME).is_dir() and any(
            (candidate / DEFAULT_SKILLS_DIRNAME).glob("*/SKILL.md")
        ):
            return candidate

    raise FileNotFoundError(
        "could not locate a skills/ directory; pass --skills-root explicitly"
    )


def iter_skill_records(
    repo_root: Path | None = None,
    skills_dirname: str = DEFAULT_SKILLS_DIRNAME,
) -> Iterable[SkillRecord]:
    """Convenience iterator that builds the manifest in-memory if absent."""

    root = repo_root or find_repo_root()
    try:
        manifest = load_manifest(root, skills_dirname)
    except FileNotFoundError:
        manifest = build_manifest(root, skills_dirname)
    yield from manifest.skills
